### ISSUE TITLE
Problem about resume my own checkpoint and some strange loss

### ISSUE THREAD

**Issue by YYZ1021** [Newbeeer/pfgmpp#7]
Hi, when I tried to resume my checkpoint, it always failed. However, when I resume your checkpoint, it was fine.

I configure the environment as you given, but I only use one 3090Ti to train the model. I use the following training config:
--outdir C:\Users\ENeS\Desktop\outputs --name train_2 --data C:\Users\ENeS\Desktop\Dataset\1\cifar10-32x32.zip --cond 0 --arch ddpmpp --pfgmpp 1 --batch 32 --aug_dim 128

I found this problem because of another problem. In tick 230, kimg=11503.7, the loss first keep normal at around 0.2, but it suddenly  become very high (over 18, just one time) and then become around 1. The loss down to around 0.7 before tick 240, after that the loss become around 1 and never go down. So I exit it, try to resume the checkpoint, and I found I cannot resume.

The error message when I resume my checkpoint is:

Setting up optimizer...
In EDM loss: D:128, N:3072
Loading training state from "C:\Users\ENeS\Desktop\outputs\train_2\training-state-010003.pt"...
Traceback (most recent call last):
  File "C:\Users\ENeS\Documents\GitHub\pfgmpp\train.py", line 255, in <module>
    main()
  File "C:\Users\ENeS\anaconda3\envs\edm\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ENeS\anaconda3\envs\edm\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\ENeS\anaconda3\envs\edm\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ENeS\anaconda3\envs\edm\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ENeS\Documents\GitHub\pfgmpp\train.py", line 248, in main
    training_loop.training_loop(**c)
  File "C:\Users\ENeS\Documents\GitHub\pfgmpp\training\training_loop.py", line 132, in training_loop
    misc.copy_params_and_buffers(src_module=data['net'], dst_module=net, require_all=True)
KeyError: 'net'

Process finished with exit code 1

Hope you can help me, thank you very much.

**Comment by Newbeeer** [comment]
Hello,

Thank you for bringing up the issue. I have also observed sudden jumps in loss during my previous experiments, and I have used the same strategy as you to resume from good checkpoints. I suspect that this issue could be due to extreme values being sampled from the beta distribution. To address this, I have added the following line: https://github.com/Newbeeer/pfgmpp/blob/afd7d3fbe4a621e22bc519e08dd8afae2695efe2/training/loss.py#L126, which confines the range. Hopefully, this will resolve the issue.

I apologize for the resuming issue. It was indeed a bug in our code. I have fixed it by also saving the net in the following line: https://github.com/Newbeeer/pfgmpp/blob/afd7d3fbe4a621e22bc519e08dd8afae2695efe2/training/training_loop.py#L218."

**Comment by YYZ1021** [comment]
Hi,

Thanks for your quick reply, I have quickly tested the resuming function, and it works well now. 

Last time it cost 20 hours to reach the 230 tick, so I cannot give you my response now. But I start training it now, if I found something new or it worked well, I will let you know.

Thanks again for your reply.

**Comment by YYZ1021** [comment]
Hi,

I have reached my last checkpoint now and I didn't see the strange loss again. Thank you very much.

**Comment by Newbeeer** [comment]
Sounds good! Thanks for reporting this. Feel free to reach out anytime if there are any other issues.

**Comment by YYZ1021** [comment]
Hi, it's me, again.

I met the same issue again. The loss suddenly became very large (this time, 89.5) and then down and kept at around 1.

I used the same configs as last time, and the issue came from tick 314, kimg 15705. My configs:
--outdir C:\Users\ENeS\Desktop\outputs --name train_2 --data C:\Users\ENeS\Desktop\Dataset\1\cifar10-32x32.zip --cond 0 --arch ddpmpp --pfgmpp 1 --batch 32 --aug_dim 128

I attach my log and screenshot here. The issue is on the log, line 489722.

![issue 2023_4_7 18_43_27](https://user-images.githubusercontent.com/78796518/230587066-9bf26427-c18b-451a-85cc-df090fc6060d.png)
[log.txt](https://github.com/Newbeeer/pfgmpp/files/11177905/log.txt)

Thank you.

**Comment by Newbeeer** [comment]
Hi,

For me, this issue occurs only once in every twenty experiments. I'm looking into this problem now. Could you provide me with the complete command line (including the options to torchrun), please?

**Comment by Newbeeer** [comment]
HI,

I'm still suspecting the issue arises from the sampling from inverse beta distribution (otherwise the code is just the same as EDM). I add more constraints to the range of inverse-beta distribution. Theoretically, its possible range is strictly confined now:
https://github.com/Newbeeer/pfgmpp/blob/acad8da44db1a2f2d04f6ea53bb37aa42c0136b9/training/loss.py#L126

Very sorry about the confusion. Please let me know the problem persists when using the updated code.

Y

**Comment by YYZ1021** [comment]
Hi,

I'm sorry that I use the Pycharm run configuration so I cannot give you the torchrun options, or should say I use the default options? 

I resumed my checkpoint and until now it didn't show this issue again. I don't know if it's because it didn't train for a long time.

Now I want to try your new code with the new checkpoint, I will post the new result here later.

Thank you.
